#!/bin/bash

for i in $(find $1 -name "*.jpg")
do
	cv_to="${i%.jpg}.png"

	width=`identify -ping -format %w $i`
	height=`identify -ping -format %h $i`

	if [ width > 128 ] || [ height > 128  ] ; then
		convert "$i" -resize 128x128 "$cv_to"
		echo "converted and resized $i to $cv_to"
	else
		convert "$i" "$cv_to"
		echo "converted $i to $cv_to"

	fi

done
